### ISSUE TITLE
Implement Mobile Optimization

### ISSUE THREAD

**Issue by cforcomputer** [UWB-ACM/uwbacm-site#33]
Building a new mobile website should take priority after the mailchimp form and alumni page have been created. 

I'm personally not sure how to modify the existing site to make it mobile friendly. However, I do know how to make a mobile optimized site from scratch. I can use react, but using a more basic layout without jsx for mobile may be easier to maintain. Thoughts?

The mobile site would be separate, mobile users would be redirected to the subdomain m.uwbacm.com which would display the version of the site built for mobile. While less painful initially, it may prove to be a pain to maintain later down the road, as we would have to update both sites separately.

It could be fun to build an actual application for mobile as well. Maintaining it could be a way of training members about mobile development. Keep track of events, submit surveys, that kind of thing (just and idea).

**Comment by bpas247** [comment]
> I'm personally not sure how to modify the existing site to make it mobile friendly.

The approach is no different from a vanilla + SASS website, via [responsive web design](https://www.w3schools.com/css/css_rwd_intro.asp).

> I can use react, but using a more basic layout without jsx for mobile may be easier to maintain. Thoughts?

I would disagree, since it would move the functionality of the website from declarative to imperative, which was one of the main goals of #13. Also, responsiveness can be implemented functionally or through styling. If implemented through styling, the responsiveness functionality of the website wouldn't be coupled to the actual functionality of the website, so there wouldn't be any clashes with whether the website's functionality was implemented through vanilla JS or React.

> The mobile site would be separate, mobile users would be redirected to the subdomain m.uwbacm.com which would display the version of the site built for mobile.

I'm personally not a fan of this design, and seems to have some [notable drawbacks](https://developer.mozilla.org/en-US/docs/Web/Guide/Mobile/Separate_sites#The_bad).

> While less painful initially, it may prove to be a pain to maintain later down the road, as we would have to update both sites separately.

I'd also like to add that it would be painful initially, since any existing open issues/tasks would be doubled at the release of the mobile-site 😛 exceptions being platform-specific issues/tasks

**Comment by cforcomputer** [comment]
Good points, I would have to agree. What I was referring to when I said I wasn't sure how to make it mobile friendly, I'm unsure how to make the current styles for the nav bar and officers section mobile friendly.

We could make it so that it changes completely after a certain resolution, and make a different version of the current style choices that is easier to understand on mobile?
