### ISSUE TITLE
Implement unit tests for specific features

### ISSUE THREAD

**Issue by etcadinfinitum** [UWB-ACM/uwbacm-site#36]
To do:

- [ ] Unit tests for external links (especially officers page)
- [ ] Unit tests for MailChimp POST requests

@bpas247 @Chris-Johnston @cforcomputer your expertise/willingness to help would be appreciated, especially regarding testing within the React framework (which is still new to me).

**Comment by bpas247** [comment]
> Unit tests for external links (especially officers page)

hmm, I'm thinking we can use an external library for that like [broken-link-checker](https://www.npmjs.com/package/broken-link-checker-local). Then we could add that as a step for our CI builds.

> Unit tests for MailChimp POST requests

I would strongly advise against that, since it would be [testing implementation details](https://kentcdodds.com/blog/testing-implementation-details). Instead, we should write unit tests for `Form` based on how we expect the end-user to interact with it.
